---

- hosts: all
  sudo: yes
  vars:
    citadel_bucket: 'balanced-citadel'

  vars_files:
    - defaults/main.yml

  roles:
    - supervisord

  handlers:
    - include: handlers/main.yml

  tasks:
    - name: install dev package
      apt: pkg={{ item }} state=installed
      with_items:
        - python-dev
        - python-setuptools

    - name: install pip
      easy_install: name=pip

    - name: install common packages
      pip: name={{ item }} state=present
      with_items:
      - ipython
      - ipdb
      - "pip>=1.5,<2.0"

    # http://hakunin.com/six-ansible-practices
    - name: ensure github.com is a known host
      tags: devpi
      lineinfile:
        dest: /root/.ssh/known_hosts
        create: yes
        state: present
        line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
        regexp: "^github\\.com"

    - name: install devpi
      sudo: yes
      include: tasks/main.yml
      tags: devpi
