---
- name: create devpi group
  group: name=devpi state=present

- name: create devpi user
  user: >
    name=devpi
    group=devpi
    password=no
    system=yes
    home={{ devpi_install_dir }}
    state=present

- name: dirs
  file: >
    path={{ item }}
    owner=devpi
    group=devpi
    state=directory
    mode=0755
  with_items:
  - "{{ devpi_install_dir }}"
  - /var/run/devpi
  - /var/log/devpi
  notify: restart devpi

- name: install server
  tags: install-server
  include: server.yml

- name: install nginx
  tags: install-nginx
  include: nginx.yml
  when: install_nginx
