---

- name: install virtualenv
  pip: name=virtualenv state=present
  notify: restart devpi

- name: create the devpi virtualenv
  command: >
    virtualenv -p /usr/bin/python {{ devpi_install_dir }}
    creates={{ devpi_install_dir }}/bin/python

- name: create the devpi data dir
  file: >
    dest={{ devpi_data_dir }}
    state=directory
    owner=devpi
    group=devpi

- name: install server
  pip: >
    name={{ item }}
    state=present
    virtualenv={{ devpi_install_dir }}
  with_items:
    - devpi-server
    - eventlet
  notify: restart devpi

- name: writing supervisor script
  template: >
    src=supervisor-devpi.conf.j2
    dest={{ supervisord_additional_conf_dir }}/devpi.conf
    owner=devpi
    group=devpi
    mode=0644
  notify: restart devpi

- name: update devpi supervisor configuration
  supervisorctl: >
    name=devpi-server
    supervisorctl_path={{ supervisord_bin_dir }}/supervisorctl
    state=present
  register: sv_out
  changed_when: sv_out.stdout is defined and sv_out.stdout != ""
