---

- name: start devpi
  supervisorctl: name=devpi-server state=present

- name: restart devpi
  supervisorctl: name=devpi-server state=restarted

- name: restart rsyslog
  service: name=rsyslog state=restarted

- name: reload rsyslog
  service: name=rsyslog state=reloaded

- name: restart nginx
  service: name=nginx state=restarted

- name: restart lighttpd
  #service: name=lighttpd state=restarted
  debug: msg="Restart lighttpd by hand"
