---

- name: start devpi
  supervisorctl: name=devpi-server state=present

- name: restart devpi
  supervisorctl: name=devpi-server state=restarted

- name: restart rsyslog
  service: name=rsyslog state=restarted

- name: reload rsyslog
  service: name=rsyslog state=reloaded

- name: restart nginx
  service: name=nginx state=restarted
